package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// SpotInterruptionSpec represents an EC2 Spot Instance Interruption Warning event.
// See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html for details.
type SpotInterruptionSpec struct {
	// Queue is the reference to the origin of the event.
	Queue QueueReference `json:"queue,omitempty"`

	// EventTimestamp is the time at which the event was generated by EventBridge.
	EventTimestamp metav1.Time `json:"eventTimestamp,omitempty"`

	// InstanceID represents the instance affected by the event.
	InstanceID string `json:"instanceID,omitempty"`

	// AvailabilityZone represents the availability zone in which the instance is running.
	AvailabilityZone string `json:"availabilityZone,omitempty"`
}

// SpotInterruptionStatus defines the observed state of SpotInterruption
type SpotInterruptionStatus struct {
	// Timestamp at which the SpotInterruption was reconciled successfully.
	// +optional
	ReconciledAt metav1.Time `json:"reconciledAt,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster

// SpotInterruption is the Schema for the spotinterruptions API
type SpotInterruption struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of SpotInterruption
	// +required
	Spec SpotInterruptionSpec `json:"spec"`

	// status defines the observed state of SpotInterruption
	// +optional
	Status SpotInterruptionStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// SpotInterruptionList contains a list of SpotInterruption
type SpotInterruptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []SpotInterruption `json:"items"`
}

// SpotInterruptionReference represents a reference to a SpotInterruption object.
type SpotInterruptionReference struct {
	// Name is the name of the SpotInterruption object.
	Name string `json:"name,omitempty"`
}

// SpotInterruptionReferenceTo returns a reference to the given SpotInterruption object.
func SpotInterruptionReferenceTo(spotInterruption SpotInterruption) SpotInterruptionReference {
	return SpotInterruptionReference{
		Name: spotInterruption.Name,
	}
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &SpotInterruption{}, &SpotInterruptionList{})
		return nil
	})
}
