# permissions for end users to view podpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spot-handler
    app.kubernetes.io/managed-by: kustomize
  name: podpolicy-viewer-role
rules:
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - podpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - podpolicies/status
  verbs:
  - get
