# permissions for end users to edit queues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spot-handler
    app.kubernetes.io/managed-by: kustomize
  name: queue-editor-role
rules:
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - queues/status
  verbs:
  - get
