---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - spotterminator.int128.github.io
  resources:
  - sqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spotterminator.int128.github.io
  resources:
  - sqs/finalizers
  verbs:
  - update
- apiGroups:
  - spotterminator.int128.github.io
  resources:
  - sqs/status
  verbs:
  - get
  - patch
  - update
