---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - podpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - queues/finalizers
  verbs:
  - update
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - queues/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptednodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptednodes/finalizers
  verbs:
  - update
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptednodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptedpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptedpods/finalizers
  verbs:
  - update
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptedpods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptions/finalizers
  verbs:
  - update
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - spotinterruptions/status
  verbs:
  - get
  - patch
  - update
