---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - sqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - sqs/finalizers
  verbs:
  - update
- apiGroups:
  - spothandler.int128.github.io
  resources:
  - sqs/status
  verbs:
  - get
  - patch
  - update
