# permissions for end users to view sqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spot-handler
    app.kubernetes.io/managed-by: kustomize
  name: sqs-viewer-role
rules:
- apiGroups:
  - spotterminator.int128.github.io
  resources:
  - sqs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spotterminator.int128.github.io
  resources:
  - sqs/status
  verbs:
  - get
