apiVersion: spothandler.int128.github.io/v1
kind: Queue
metadata:
  labels:
    app.kubernetes.io/name: spot-handler
    app.kubernetes.io/managed-by: kustomize
  name: queue-sample
spec:
  url: https://sqs.us-east-2.amazonaws.com/123456789012/test-queue
  spotInterruption:
    podTermination:
      # Enabled indicates whether to terminate a Pod when the Node is interrupted.
      # Default is false.
      enabled: true

      # DelaySeconds is the delay before terminating the Pod.
      # The default is 0 (immediately).
      delaySeconds: 30

      # GracePeriodSeconds overrides the Pod terminationGracePeriodSeconds.
      # No override by default.
      gracePeriodSeconds: 30
