name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'
      - Makefile
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'
      - Makefile

jobs:
  go:
    uses: int128/kubebuilder-workflows/.github/workflows/go.yaml@af0ac48fdce86f572a8c9053e0d9bd842be9c834 # v1.0.0
    permissions:
      contents: write
      pull-requests: write
    with:
      go-version: 1.23.1
      golangci-lint-version: v1.61.0
