name: manifest

on:
  pull_request:
    paths:
      - config/**
      - .github/workflows/manifest.yaml

jobs:
  manifest:
    uses: int128/kubebuilder-workflows/.github/workflows/manifest.yaml@af0ac48fdce86f572a8c9053e0d9bd842be9c834 # v1.0.0
    permissions:
      contents: read
      pull-requests: write
