name: manifest

on:
  pull_request:
    paths:
      - config/**
      - .github/workflows/manifest.yaml

jobs:
  manifest:
    uses: int128/kubebuilder-workflows/.github/workflows/manifest.yaml@4587f3945e2c3de18805dd46351e1ed1f2640604 # v1.4.1
    permissions:
      contents: read
      pull-requests: write

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: kind create cluster
      - run: kustomize build config/crd | kubectl apply -f -
      - run: sleep 5
      - run: kustomize build config/samples | kubectl apply -f -
