name: manifest

on:
  pull_request:
    paths:
      - config/**
      - .github/workflows/manifest.yaml

jobs:
  manifest:
    uses: int128/kubebuilder-workflows/.github/workflows/manifest.yaml@e4ad31a438f188f70bde87827a8dbe466e623dea # v1.5.0
    permissions:
      contents: read
      pull-requests: write

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: kind create cluster
      - run: kustomize build config/crd | kubectl apply -f -
      - run: sleep 5
      - run: kustomize build config/samples | kubectl apply -f -
