name: release

on:
  push:
    tags:
      - v*
  pull_request:
    paths:
      - config/**
      - .github/workflows/release.yaml

jobs:
  manifest:
    uses: int128/kubebuilder-workflows/.github/workflows/release.yaml@081412b6598ba94c15151a391adce0f74ecbce12 # v1
    permissions:
      contents: write
